server:
  port: 8080
service:
  url:
    location: http://localhost:8000
    question_response: http://localhost:8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: postgres
    platform: postgres